modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
[[mods]]
modId="bigbuckets"
version="${file.jarVersion}"
displayName="Big Buckets"
updateJSONURL="https://raw.githubusercontent.com/williambl/bigbuckets/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bigbuckets"
logoFile="assets/bigbuckets/icon.png"
credits=""
authors="Will BL"
description='''
This mod adds an upgradable bucket. It can store any fluid, and stores more than the regular bucket can.
'''
[[dependencies.bigbuckets]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bigbuckets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
