modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="bigbuckets"
version="${file.jarVersion}"
displayName="Big Buckets"
updateJSONURL="https://raw.githubusercontent.com/williambl/bigbuckets/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bigbuckets"
logoFile="assets/bigbuckets/icon.png"
credits=""
authors="Will BL"
description='''
This mod adds an upgradable bucket. It can store any fluid, and stores more than the regular bucket can.
'''
[[dependencies.bigbuckets]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bigbuckets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
